name: Branch Update Check

on:
  push:
    branches: [ "main", "Debug-Mixed-Code" ]
  pull_request:
    branches: [ "main", "Debug-Mixed-Code" ]

jobs:
  bypass-check:
    name: Bypass Check
    runs-on: ubuntu-latest
    steps:
      - name: Auto-pass
        run: echo "Work!"
